# Generated by Django 2.0.4 on 2018-04-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificarusuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellasusuario', models.IntegerField(db_column='ESTRELLASUSUARIO')),
                ('comentariousuario', models.CharField(blank=True, db_column='COMENTARIOUSUARIO', max_length=200, null=True)),
            ],
            options={
                'db_table': 'calificarusuario',
            },
        ),
        migrations.CreateModel(
            name='Canchas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecancha', models.CharField(db_column='NOMBRECANCHA', max_length=25)),
                ('telefonocancha', models.IntegerField(db_column='TELEFONOCANCHA')),
                ('diasdisponible', models.CharField(db_column='DIASDISPONIBLE', max_length=60)),
                ('horaabrir', models.TimeField(db_column='HORAABRIR')),
                ('horacerrar', models.TimeField(db_column='HORACERRAR')),
                ('ubicacion', models.CharField(db_column='UBICACION', max_length=50)),
                ('tarifa', models.IntegerField(db_column='TARIFA')),
                ('caracteristicas', models.CharField(db_column='CARACTERISTICAS', max_length=100)),
            ],
            options={
                'db_table': 'canchas',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreciudad', models.CharField(db_column='NOMBRECIUDAD', max_length=15)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredepartamento', models.CharField(db_column='NOMBREDEPARTAMENTO', max_length=15)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correofeed', models.CharField(db_column='CORREOFEED', max_length=50)),
                ('mensajefeed', models.CharField(db_column='MENSAJEFEED', max_length=200)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreimagen', models.CharField(db_column='NOMBREIMAGEN', max_length=52)),
                ('imagenpath', models.CharField(db_column='IMAGENPATH', max_length=1024)),
                ('canchas_idcancha', models.ForeignKey(db_column='canchas_IDCANCHA', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Canchas')),
            ],
            options={
                'db_table': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='Imagenverif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreimagenverif', models.CharField(db_column='NOMBREIMAGENVERIF', max_length=52)),
                ('imagenverifpath', models.CharField(db_column='IMAGENVERIFPATH', max_length=1024)),
            ],
            options={
                'db_table': 'imagenverif',
            },
        ),
        migrations.CreateModel(
            name='Reservarcancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horainicio', models.DateTimeField(db_column='HORAINICIO')),
                ('horafin', models.DateTimeField(db_column='HORAFIN')),
                ('estado', models.IntegerField(db_column='ESTADO')),
                ('canchas_idcancha', models.ForeignKey(db_column='canchas_IDCANCHA', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Canchas')),
            ],
            options={
                'db_table': 'reservarcancha',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinusuario', models.CharField(db_column='PINUSUARIO', max_length=6, unique=True)),
                ('nombreusuario', models.CharField(db_column='NOMBREUSUARIO', max_length=255)),
                ('correousuario', models.CharField(db_column='CORREOUSUARIO', max_length=255)),
                ('passwordusuario', models.CharField(db_column='PASSWORDUSUARIO', max_length=100)),
                ('celularusuario', models.BigIntegerField(db_column='CELULARUSUARIO')),
                ('rol', models.IntegerField(db_column='ROL')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Calificarcancha',
            fields=[
                ('usuario_idusuario', models.ForeignKey(db_column='usuario_IDUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.Usuario')),
                ('estrellascancha', models.IntegerField(db_column='ESTRELLASCANCHA')),
                ('comentariocancha', models.CharField(blank=True, db_column='COMENTARIOCANCHA', max_length=200, null=True)),
            ],
            options={
                'db_table': 'calificarcancha',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad_idciudad',
            field=models.ForeignKey(blank=True, db_column='ciudad_IDCIUDAD', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Ciudad'),
        ),
        migrations.AddField(
            model_name='reservarcancha',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_IDUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='imagenverif',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_IDUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento_iddepartamento',
            field=models.ForeignKey(db_column='departamento_IDDEPARTAMENTO', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Departamento'),
        ),
        migrations.AddField(
            model_name='canchas',
            name='ciudad_idciudad',
            field=models.ForeignKey(db_column='ciudad_IDCIUDAD', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Ciudad'),
        ),
        migrations.AddField(
            model_name='canchas',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_IDUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='calificarusuario',
            name='usuario_idusuariocalif',
            field=models.ForeignKey(db_column='usuario_IDUSUARIOCALIF', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuario'),
        ),
        migrations.AddField(
            model_name='calificarcancha',
            name='canchas_idcancha',
            field=models.ForeignKey(db_column='canchas_IDCANCHA', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Canchas'),
        ),
    ]
