# Generated by Django 2.0.4 on 2018-04-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificarcancha',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificarcancha',
            name='usuario_idusuario',
            field=models.ForeignKey(db_column='usuario_IDUSUARIO', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Usuario'),
        ),
    ]
