# Generated by Django 2.0.4 on 2018-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180409_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rola',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pinusuario',
            field=models.CharField(db_column='PINUSUARIO', max_length=6),
        ),
    ]
