# Generated by Django 2.0.4 on 2018-04-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180409_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rola',
        ),
    ]
